version: '3'

services:
  app:
    build: .
    ports:
      - '8081:8081'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    privileged: true
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ppt
      MONGO_USERNAME: scodfield
      MONGO_PASSWORD: 123456
    volumes:
      - /home/ppt/mongo/data:/data/db
      - ./script/mongo_init.sh:/docker-entrypoint-initdb.d/mongo_init.sh
    networks:
      - ppt-net
    command:
      mongod --port 27017 --bind_ip_all --auth

networks:
  ppt-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16