version: '3.8'

services:
  app:
    build: .
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ppt
      MONGO_USERNAME: scodfield
      MONGO_PASSWORD: 123456
    volumes:
      - /home/ppt/mongo/data:/data/db
      - ./script/mongo_init.sh:/docker-entrypoint-initdb.d/mongo_init.sh
    command:
      - --auth